export const VIDEO_REQUEST = "VIDEO_REQUEST";
export const VIDEO_SUGGESTIONS_REQUEST = "VIDEO_SUGGESTIONS_REQUEST";
export const VIDEO_SUCCESS = "VIDEO_SUCCESS";
export const VIDEO_FAILURE = "VIDEO_FAILURE";
